version: 0.0
os: linux
files:
  - source: /pandemic
    destination: /pandemic
hooks:
  BeforeInstall:
    - location: install_dependencies

  AfterInstall:
    - location: scripts/start_server
      timeout: 300